import { RideRecord } from '../types';

/**
 * Generate an HTML receipt suitable for printing to PDF via expo-print.
 */
export function generateReceiptHTML(
    ride: RideRecord,
    currencySymbol: string,
    driverName: string
): string {
    const startDate = new Date(ride.startTime);
    const endDate = new Date(ride.endTime);
    const dateStr = startDate.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
    const startTimeStr = startDate.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
    });
    const endTimeStr = endDate.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
    });

    const durationMin = Math.ceil(
        (ride.movingTimeSeconds + ride.waitingTimeSeconds) / 60
    );
    const waitingMin = (ride.waitingTimeSeconds / 60).toFixed(1);
    const fp = ride.fareProfileUsed;

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1a1a2e;
      padding: 40px;
      max-width: 400px;
      margin: 0 auto;
    }
    .header { text-align: center; margin-bottom: 32px; }
    .header h1 { font-size: 24px; font-weight: 700; }
    .header p { color: #666; margin-top: 4px; font-size: 14px; }
    .divider { border-top: 1px dashed #ccc; margin: 16px 0; }
    .info-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
    .info-row .label { color: #666; }
    .info-row .value { font-weight: 500; }
    .section-title { font-size: 12px; font-weight: 600; color: #999; text-transform: uppercase; letter-spacing: 1px; margin: 16px 0 8px; }
    .fare-row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 15px; }
    .fare-row .detail { color: #666; }
    .total-row { display: flex; justify-content: space-between; padding: 12px 0; font-size: 20px; font-weight: 700; border-top: 2px solid #1a1a2e; margin-top: 8px; }
    .total-row .amount { color: #00B87D; }
    .footer { text-align: center; margin-top: 32px; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚕 Ride Receipt</h1>
    ${driverName ? `<p>${driverName}</p>` : ''}
  </div>

  <div class="section-title">Ride Details</div>
  <div class="info-row"><span class="label">Date</span><span class="value">${dateStr}</span></div>
  <div class="info-row"><span class="label">Time</span><span class="value">${startTimeStr} – ${endTimeStr}</span></div>
  <div class="info-row"><span class="label">Duration</span><span class="value">${durationMin} min</span></div>
  <div class="info-row"><span class="label">Distance</span><span class="value">${ride.distanceMiles.toFixed(2)} mi</span></div>
  <div class="info-row"><span class="label">Waiting Time</span><span class="value">${waitingMin} min</span></div>
  <div class="info-row"><span class="label">Rate Profile</span><span class="value">${fp.name}</span></div>

  <div class="divider"></div>

  <div class="section-title">Fare Breakdown</div>
  <div class="fare-row"><span>Base Fare</span><span>${currencySymbol}${ride.fareBreakdown.baseFare.toFixed(2)}</span></div>
  <div class="fare-row">
    <span>Distance <span class="detail">(${ride.distanceMiles.toFixed(2)} mi × ${currencySymbol}${fp.perMileRate.toFixed(2)})</span></span>
    <span>${currencySymbol}${ride.fareBreakdown.distanceCharge.toFixed(2)}</span>
  </div>
  <div class="fare-row">
    <span>Waiting <span class="detail">(${waitingMin} min × ${currencySymbol}${fp.waitingRatePerMinute.toFixed(2)})</span></span>
    <span>${currencySymbol}${ride.fareBreakdown.waitingCharge.toFixed(2)}</span>
  </div>

  <div class="total-row">
    <span>Total</span>
    <span class="amount">${currencySymbol}${ride.totalFare.toFixed(2)}</span>
  </div>

  <div class="footer">
    <p>Generated by TaxiMeter</p>
  </div>
</body>
</html>
`;
}

/**
 * Generate a plain-text summary for sharing via text/messaging.
 */
export function generateReceiptText(
    ride: RideRecord,
    currencySymbol: string,
    driverName: string
): string {
    const startDate = new Date(ride.startTime);
    const fp = ride.fareProfileUsed;
    const waitingMin = (ride.waitingTimeSeconds / 60).toFixed(1);
    const durationMin = Math.ceil(
        (ride.movingTimeSeconds + ride.waitingTimeSeconds) / 60
    );

    let text = '🚕 Ride Receipt\n';
    text += '─'.repeat(30) + '\n';
    if (driverName) text += `Driver: ${driverName}\n`;
    text += `Date: ${startDate.toLocaleDateString()}\n`;
    text += `Duration: ${durationMin} min\n`;
    text += `Distance: ${ride.distanceMiles.toFixed(2)} mi\n`;
    text += `Waiting: ${waitingMin} min\n`;
    text += '─'.repeat(30) + '\n';
    text += `Base Fare:     ${currencySymbol}${ride.fareBreakdown.baseFare.toFixed(2)}\n`;
    text += `Distance:      ${currencySymbol}${ride.fareBreakdown.distanceCharge.toFixed(2)}\n`;
    text += `Waiting:       ${currencySymbol}${ride.fareBreakdown.waitingCharge.toFixed(2)}\n`;
    text += '─'.repeat(30) + '\n';
    text += `TOTAL:         ${currencySymbol}${ride.totalFare.toFixed(2)}\n`;

    return text;
}
